### ISSUE TITLE
Deepstream SDK on Jetson TX2

### ISSUE THREAD

**Issue by komalpharate** [ghostbbbmt/NVIDIA-DeepStreamSDK#1]
Hi,
I want to know about the C++ APIs available for above setup

**Comment by hoanglehaithanh** [comment]
The SDK in my repo is being deployed and run on a Tesla P4, not a Jetson. You can visit NVIDIA DevTalk forum for more details because there are some differences between two platforms. I am not similar to Jetson so I don't have any information to share :(

Sorry for this late reply, hope you have had your answer.
